import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link";
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { ViajeDetails } from '../components/viaje.tsx'
import { data } from "../data/data.ts";

const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Viajes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <ViajeDetails destino={data[0]}/>
      <ViajeDetails destino={data[1]}/>
      <ViajeDetails destino={data[2]}/>
      <ViajeDetails destino={data[3]}/>
      <ViajeDetails destino={data[4]}/>
      </main>
    </>
  )
}
